### ISSUE TITLE
level=error msg="login error: invalid_argument"

### ISSUE THREAD

**Issue by SingingDalong** [52funny/pikpakupload#1]
**_level=error msg="login error: invalid_argument"_**

I use windows. Is it not available on Windows?

config.yml
+1xxxxxxxxxx:
xxxxxxxxx:

**Comment by 52funny** [comment]
In the yml file, you should keep the key, not deleting.
like this:
```yml
username: +861xxxxxxxxx
password: xxxxxx
```

**Comment by SingingDalong** [comment]
> In the yml file, you should keep the key, not deleting. like this:
> 
> ```yaml
> username: +861xxxxxxxxx
> password: xxxxxx
> ```

Thank you. It works fine.

**Comment by 52funny** [comment]
Also i'm upload the windows executable file in release page.
