### ISSUE TITLE
Upload specific folder

### ISSUE THREAD

**Issue by SingingDalong** [52funny/pikpakupload#2]
Can't upload specific folders?
ex: pikpakupload.exe D:\Movies -p Movies

**Comment by 52funny** [comment]
You should change the order of the parameters. like this:
```bash
pikpakupload.exe -p Movies D:\Movies
```

**Comment by SingingDalong** [comment]
> You should change the order of the parameters. like this:
> 
> ```shell
> pikpakupload.exe -p Movies D:\Movies
> ```

Thank you. It works fine.

**Comment by 52funny** [comment]
You're welcome
