### ISSUE TITLE
能否加一个下载的功能

### ISSUE THREAD

**Issue by wellmoon** [52funny/pikpakupload#3]

**Comment by 52funny** [comment]
可以考虑一下的💭

**Comment by 52funny** [comment]
可能会新建一个仓库 `pikpakcli` ，一个关于 pikpak 的命令行工具，它应该会具备一下功能：
+ 上传
+ 下载

可能后期也会加入 `webdav` 的功能。

如果你还有什么好的建议的话，我也会考虑加入的！

**Comment by 52funny** [comment]
可以参考新的项目 [pikpakcli](https://github.com/52funny/pikpakcli)
可以进行下载
