### ISSUE TITLE
能否支持上传文件夹

### ISSUE THREAD

**Issue by pongfcnkl** [52funny/pikpakupload#4]
现在只能上传文件，上传文件夹没有目录。

**Comment by 52funny** [comment]
你是指新建文件夹么？

**Comment by 52funny** [comment]
可以参考新的项目 [pikpakcli](https://github.com/52funny/pikpakcli)
可以新建文件夹

**Comment by pongfcnkl** [comment]
我的意思是上传文件夹会导致不上传目录
像这样所有本地文件夹里的文件全在网盘里同一个文件夹里了
![截图_20221221220408](https://user-images.githubusercontent.com/24273319/208923813-9b9f522f-4257-44c7-9c60-32766dadd796.png)
![截图_20221221220817](https://user-images.githubusercontent.com/24273319/208924520-6aa96b19-9351-4739-95f5-813af17a7361.png)

**Comment by 52funny** [comment]
你用的命令是啥？

**Comment by 52funny** [comment]
如果要上传目录的话，你应该在父目录里面上传。这样会自动创建文件夹的。

**Comment by pongfcnkl** [comment]
命令是 pikpakupload -p Upload D:\....
